Add a TECH_PREVIEW doc section on the NIC Configuration Operator depl…
Mellanox/network-operator-docs pull request #126
Opened 2024-11-04 16:49 UTC by almaslennikov

…oyment

2024-11-05 13:35 UTC, e0ne requested changes
Please make commit message title shorter. Also few nits are added below

2024-11-05 13:35 UTC, e0ne commented on docs/getting-started-kubernetes.rst
> +[TECH PREVIEW ] Configure NIC Firmware using the NIC Configuration Operator
please remove space before `]`

2024-11-05 13:35 UTC, e0ne commented on docs/getting-started-kubernetes.rst
> +`NVIDIA NIC Configuration Operator <https://github.com/Mellanox/nic-configuration-operator>`_ provides Kubernetes API (Custom Resource Definition) to allow FW configuration on Nvidia NICs in a coordi
`Nvidia` -> `NVIDIA`

2024-11-05 15:32 UTC, rollandf approved these changes

2024-11-06 07:43 UTC, e0ne approved these changes

2024-11-06 07:43 UTC, merged